################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
[en.params]
home = "Home"
copyright = "Copyright &copy; 2025 Designed & Developed by aex"



################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
[fr.params]
home = "Accueil"
copyright = "Copyright &copy; 2025 Designed & Developed by aex"





