################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
[en.params]
home = "Home"
copyright = "Copyright &copy; 2025 Designed & Developed by aex"



################################### chinese language #####################################
[hk]
languageName = "hk"
languageCode = "zh-hk"
contentDir = "content/chinese"
weight = 2
[hk.params]
home = "Accueil"
copyright = "Copyright &copy; 2025 Designed & Developed by aex"





