################### Traditional Chinese Navigation ########################
[[main]]
name = "首頁"
url = "#home"
weight = 1

[[main]]
name = "關於我們"
url = "#about"
weight = 2

[[main]]
name = "團隊"
url = "#team"
weight = 3

[[main]]
name = "聯繫我們"
url = "#contact"
weight = 4 