################### English Navigation ########################
[[main]]
name = "home"
url = "#home"
weight = 1

[[main]]
name = "about"
url = "#about"
weight = 2

[[main]]
name = "team"
url = "#team"
weight = 3

[[main]]
name = "contact"
url = "#contact"
weight = 4

