
################### French Navigation ########################
[[main]]
name = "sur"
url = "#about"
weight = 1

[[main]]
name = "un service"
url = "#services"
weight = 2

[[main]]
name = "portefeuille"
url = "#portfolio"
weight = 3

[[main]]
name = "équipe"
url = "#team"
weight = 4

[[main]]
name = "tarification"
url = "#pricing"
weight = 5

[[main]]
name = "blog"
url = "#blog"
weight = 6

[[main]]
name = "contact"
url = "#contact"
weight = 7

[[main]]
name = "themefisher"
url = "https://themefisher.com/"
weight = 8